<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PaquetesSeeder extends Seeder
{
    public function run()
    {
        $cuadrosNotas = [
            'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
            'Nota: +20 alumnos → cuadro de vidrio 45x30 para el docente',
            'Nota: -12 alumnos → sesión en una sola fecha',
        ];

        $anuariosNotas = [
            'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
            'Nota: +20 alumnos → anuario para el docente',
            'Nota: -12 alumnos → sesión en una sola fecha',
        ];

        $data = [

            // ════════════════════════════════════════════════════════════════
            // NIVEL: INICIAL
            // ════════════════════════════════════════════════════════════════

            // ── Cuadros Inicial — S/110 (33x45 cm) ───────────────────────────
            [
                'nombre_paquete'   => 'Cuadro Soy una Princesa',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 110.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 33 cm x 45 cm.',
                    '3 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme o familia',
                    '1 sesión en el centro educativo (lunes a viernes)',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Soy un Super Héroe',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 110.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 33 cm x 45 cm.',
                    '3 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme o familia',
                    '1 sesión en el centro educativo (lunes a viernes)',
                ], $cuadrosNotas)),
            ],

            // ── Cuadros Inicial — S/140 (58.5x45.5 cm) ───────────────────────
            [
                'nombre_paquete'   => 'Cuadro Mi Princesa',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 140.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 58.5 cm x 45.5 cm. Diseño Mi Princesa.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual o familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Soy el Mejor',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 140.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 58.5 cm x 45.5 cm. Diseño Soy el Mejor.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual o familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Princesas Mágicas',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 140.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 58.5 cm x 45.5 cm. Diseño Princesas Mágicas.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual o familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Super Héroe',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 140.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 58.5 cm x 45.5 cm. Diseño Super Héroe.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual o familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],

            // ── Cuadros Inicial — S/160 premium (50.5x51 cm) ─────────────────
            [
                'nombre_paquete'   => 'Cuadro Mi Príncipe Super Capy',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 160.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 51 cm. Diseño premium Mi Príncipe Super Capy.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual',
                    '1 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Mi Princesa Capy Princess',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 160.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 51 cm. Diseño premium Mi Princesa Capy Princess.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual',
                    '1 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Barbie Capibara',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 160.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 51 cm. Diseño premium Barbie Capibara.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual',
                    '1 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Avenger',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Cuadros',
                'precio'           => 160.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 51 cm. Diseño premium Avenger.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con casual',
                    '1 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],

            // ── Anuarios Inicial ──────────────────────────────────────────────
            [
                'nombre_paquete'   => 'Anuario Medium Inicial',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Anuarios',
                'precio'           => 145.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 20x25cm, 5 hojas, 10 páginas.',
                    '10 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '3 con toga',
                    '2 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Big Inicial',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Anuarios',
                'precio'           => 150.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 25x25cm, 5 hojas, 10 páginas.',
                    '12 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '2 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con vestimenta casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Big Premium Inicial',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Anuarios',
                'precio'           => 180.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 25x25cm, 6 hojas, 12 páginas.',
                    '15 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '3 con toga',
                    '2 grupal',
                    '2 con uniforme',
                    '2 con ropa sport',
                    '2 con vestimenta casual',
                    '4 con familia',
                    '3 sesiones: centro educativo (lun-vie), exteriores y estudio',
                    'Hoja de guarda al inicio y final del anuario',
                    'Anuario en versión digital',
                    'Caja de cartulina folcodte para su protección',
                ], $anuariosNotas)),
            ],

            // ── Packs Inicial ─────────────────────────────────────────────────
            [
                'nombre_paquete'   => 'Pack Mi Primera Promo',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Paquetes',
                'precio'           => 240.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack completo para promoción de inicial.',
                    '10 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '2 con casual',
                    '2 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    'Anuario 25cm x 25cm con caja de cartulina folcodte para su protección',
                    'Anuario versión llavero 5cm x 5cm',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → cuadro de vidrio 45x30 para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Mis Recuerdos Inicial',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Paquetes',
                'precio'           => 320.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack con anuario, cuadro y cobertura de fiesta de promoción.',
                    '12 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '3 con casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    '1 Anuario 25x25 con caja de cartulina folcodte y versión llavero',
                    '1 Cuadro a elección del catálogo Inicial',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → anuario para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Premium Inicial',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Paquetes',
                'precio'           => 360.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack premium con anuario, cuadro, USB y cobertura completa de fiesta.',
                    '12 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '3 con casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    '1 Anuario 25cm x 25cm con caja de cartulina folcodte y versión llavero',
                    '1 Cuadro a elección del catálogo Inicial + 1 USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales enviadas al correo',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Video Clip de las sesiones de fotos',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → anuario para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Premium Gold Inicial',
                'nivel_disponible' => 'inicial',
                'categoria'        => 'Paquetes',
                'precio'           => 420.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack todo incluido con cobertura profesional de fiesta, 2 fotógrafos y 2 camarógrafos.',
                    '15 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '2 grupal',
                    '2 con uniforme',
                    '3 con sport',
                    '3 con casual',
                    '3 con familia',
                    '3 sesiones: centro educativo (lun-vie), exteriores y estudio',
                    '1 Anuario 25cm x 25cm con caja de cartulina folcodte para su protección',
                    '1 Anuario versión llavero',
                    '1 Cuadro a elección del catálogo Inicial',
                    'Book anillado de Firma',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 4h / 2 fotógrafos',
                    '18 fotos digitales individuales y grupales enviadas al correo',
                    '10 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 4h / 2 camarógrafos',
                    'Video entrevista por alumno',
                    'Video Clip de las sesiones de fotos',
                    'Drone para la fiesta de promoción',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 120 minutos',
                    'Cortesía: asesoría en planificación del evento, asistencia a dos reuniones',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → cuadro de vidrio 45x30 para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],

            // ════════════════════════════════════════════════════════════════
            // NIVEL: PRIMARIA
            // ════════════════════════════════════════════════════════════════

            // ── Cuadros Primaria ──────────────────────────────────────────────
            [
                'nombre_paquete'   => 'Cuadro Maravillas del Mundo',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 110.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 33 cm x 45 cm.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia o solo',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Académico',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 145.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 58.5 cm x 45.5 cm.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con ropa sport o vestimenta casual',
                    '1 con familia o solo',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Blanco Premium Brillante',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 150.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 52 cm x 67 cm.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia o solo',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Brillante',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 150.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 66 cm. Colores: Azul, Dorado, Blanco, Negro, Verde, Fucsia, Guinda.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia',
                    '1 ropa sport',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadro Encajoado',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 160.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 66 cm. Colores: White, Black, Brown, Blue.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia',
                    '1 ropa sport',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],

            // ── Anuarios Primaria ─────────────────────────────────────────────
            [
                'nombre_paquete'   => 'Anuario Small',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 135.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 20x20cm, 5 hojas, 10 páginas.',
                    '8 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Medium Primaria',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 145.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 20x25cm, 5 hojas, 10 páginas.',
                    '10 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '3 con toga',
                    '2 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Big Primaria',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 150.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 25x25cm, 5 hojas, 10 páginas.',
                    '12 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '2 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con vestimenta casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Big Premium Primaria',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 210.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 25x30cm, 6 hojas, 12 páginas.',
                    '15 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '3 con toga',
                    '2 grupal',
                    '2 con uniforme',
                    '2 con ropa sport',
                    '2 con vestimenta casual',
                    '4 con familia',
                    '3 sesiones: centro educativo (lun-vie), exteriores y estudio',
                    'Hoja de guarda al inicio y final del anuario',
                    'Anuario en versión digital',
                    'Caja de cartulina folcodte para su protección',
                ], $anuariosNotas)),
            ],

            // ── Packs Primaria ────────────────────────────────────────────────
            [
                'nombre_paquete'   => 'Pack Adiós Primaria',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 240.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack completo para promoción de primaria.',
                    '10 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '2 con casual',
                    '2 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    'Anuario 25cm x 25cm con caja de cartulina folcodte para su protección',
                    'Anuario versión llavero 5cm x 5cm',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → cuadro de vidrio 45x30 para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Mis Recuerdos Primaria',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 310.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack con anuario, cuadro y cobertura de fiesta de promoción.',
                    '12 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '3 con casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    '1 Anuario 25x25 con caja de cartulina folcodte y versión llavero',
                    '1 Cuadro 33cm x 45cm',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → anuario para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Premium Primaria',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 350.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack premium con anuario, cuadro, USB y cobertura completa de fiesta.',
                    '12 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '3 con casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    '1 Anuario 25cm x 25cm con caja de cartulina folcodte y versión llavero',
                    '1 Cuadro 33cm x 45cm + 1 USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales enviadas al correo',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Video Clip de las sesiones de fotos',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → anuario 25cm x 25cm para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Premium Gold Primaria',
                'nivel_disponible' => 'primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 420.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack todo incluido con cobertura profesional de fiesta, 2 fotógrafos y 2 camarógrafos.',
                    '15 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '2 grupal',
                    '2 con uniforme',
                    '3 con sport',
                    '3 con casual',
                    '3 con familia',
                    '3 sesiones: centro educativo (lun-vie), exteriores y estudio',
                    '1 Anuario 25cm x 25cm con caja de cartulina folcodte para su protección',
                    '1 Anuario versión llavero',
                    '1 Cuadro Brillante',
                    'Book anillado de Firma',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 4h / 2 fotógrafos',
                    '18 fotos digitales individuales y grupales enviadas al correo',
                    '10 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 4h / 2 camarógrafos',
                    'Video entrevista por alumno',
                    'Video Clip de las sesiones de fotos',
                    'Drone para la fiesta de promoción',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 120 minutos',
                    'Cortesía: asesoría en planificación del evento, asistencia a dos reuniones',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → cuadro de vidrio 45x30 para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
        ];

        $this->db->table('paquetes')->insertBatch($data);
    }
}
