<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PaquetesSeeder extends Seeder
{
    public function run()
    {
        $anuariosNotas = [
            'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
            'Nota: +20 alumnos → anuario personalizado para el docente',
            'Nota: -12 alumnos → sesión en una sola fecha',
        ];

        $cuadrosNotas = [
            'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
            'Nota: +20 alumnos → cuadro personalizado 45x30 para el docente',
            'Nota: -12 alumnos → sesión en una sola fecha',
        ];

        $data = [
            // ── ANUARIOS ─────────────────────────────────────────────────────
            [
                'nombre_paquete'   => 'Anuario Small',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 135.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 20x20cm, 5 hojas, 10 páginas.',
                    '8 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con familia',
                    '1 sesión en el centro educativo (lunes a viernes)',
                    '1 sesión en exterior o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Medium',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 145.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 20x25cm, 5 hojas, 10 páginas.',
                    '10 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '3 con toga',
                    '2 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con familia',
                    '1 sesión en el centro educativo (lunes a viernes)',
                    '1 sesión en exterior o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Big',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 150.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 25x25cm, 5 hojas, 10 páginas.',
                    '12 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '2 grupal',
                    '1 con uniforme',
                    '2 con ropa sport',
                    '2 con vestimenta casual',
                    '3 con familia',
                    '1 sesión en el centro educativo (lunes a viernes)',
                    '1 sesión en exterior o estudio',
                ], $anuariosNotas)),
            ],
            [
                'nombre_paquete'   => 'Anuario Big Premium',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Anuarios',
                'precio'           => 210.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Portada foto laminada y biocuero. 25x30cm, 6 hojas, 12 páginas.',
                    '15 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '3 con toga',
                    '2 grupal',
                    '2 con uniforme',
                    '2 con ropa sport',
                    '2 con vestimenta casual',
                    '4 con familia',
                    '3 sesiones: centro educativo (lun-vie), exteriores y estudio',
                    'Hoja de guarda al inicio y final del anuario',
                    'Anuario en versión digital',
                    'Caja de cartulina folcodte para su protección',
                ], $anuariosNotas)),
            ],

            // ── CUADROS ──────────────────────────────────────────────────────
            [
                'nombre_paquete'   => 'Maravillas del Mundo Basic',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 110.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 33 cm x 45 cm.',
                    '3 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia o solo',
                    '1 sesión de fotos',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Maravillas del Mundo',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 110.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 33 cm x 45 cm.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia o solo',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Academico',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 145.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 58.5 cm x 45.5 cm.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con ropa sport o vestimenta casual',
                    '1 con familia o solo',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Blanco Premium Brillante',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 150.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 52 cm x 67 cm.',
                    '4 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia o solo',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadros Brillante',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 150.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 66 cm. Colores: Azul, Dorado, Blanco, Negro, Verde, Fucsia, Guinda.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia',
                    '1 ropa sport',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],
            [
                'nombre_paquete'   => 'Cuadros Encajoados',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Cuadros',
                'precio'           => 160.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", array_merge([
                    'Acabado Brillante y Vidrio. 50.5 cm x 66 cm. Colores: White, Black, Brown, Blue.',
                    '5 fotos incluidas (toga para foto individual, no para foto grupal)',
                    '1 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '1 con familia',
                    '1 ropa sport',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                ], $cuadrosNotas)),
            ],

            // ── PAQUETES COMBINADOS ───────────────────────────────────────────
            [
                'nombre_paquete'   => 'Pack Adios Primaria',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 240.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack completo para promoción de primaria.',
                    '10 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '2 con casual',
                    '2 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    'Anuario 25cm x 25cm con caja de cartulina folcodte para su protección',
                    'Anuario versión llavero 5cm x 5cm',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → cuadro de vidrio 45x30 para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Mis Recuerdos',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 310.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack con anuario, cuadro y cobertura de fiesta de promoción.',
                    '12 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '3 con casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    '1 Anuario 25x25 con caja de cartulina folcodte y versión llavero',
                    '1 Cuadro 33cm x 45cm',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → anuario para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Premium',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 350.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack premium con anuario, cuadro, USB y cobertura completa de fiesta.',
                    '12 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '1 grupal',
                    '1 con uniforme',
                    '2 con sport',
                    '3 con casual',
                    '3 con familia',
                    '2 sesiones: centro educativo (lun-vie) y exteriores o estudio',
                    '1 Anuario 25cm x 25cm con caja de cartulina folcodte y versión llavero',
                    '1 Cuadro 33cm x 45cm + 1 USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 3h y media',
                    '15 fotos digitales individuales y grupales enviadas al correo',
                    '6 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 3h y media',
                    'Video Clip de las sesiones de fotos',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 90 minutos',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → anuario 25cm x 25cm para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
            [
                'nombre_paquete'   => 'Pack Premium Gold',
                'nivel_disponible' => 'inicial-primaria',
                'categoria'        => 'Paquetes',
                'precio'           => 420.00,
                'estado'           => 'ACTIVO',
                'descripcion'      => implode("\n", [
                    'Pack todo incluido con cobertura profesional de fiesta, 2 fotógrafos y 2 camarógrafos.',
                    '15 fotos digitales incluidas (toga para foto individual, no para foto grupal)',
                    '2 con toga',
                    '2 grupal',
                    '2 con uniforme',
                    '3 con sport',
                    '3 con casual',
                    '3 con familia',
                    '3 sesiones: centro educativo (lun-vie), exteriores y estudio',
                    '1 Anuario 25cm x 25cm con caja de cartulina folcodte para su protección',
                    '1 Anuario versión llavero',
                    '1 Cuadro Brillante',
                    'Book anillado de Firma',
                    'USB con las fotos y video',
                    'Fotos fiesta de promoción: cobertura 4h / 2 fotógrafos',
                    '18 fotos digitales individuales y grupales enviadas al correo',
                    '10 impresas en tamaño 10x15',
                    'Video fiesta de promoción: cobertura 4h / 2 camarógrafos',
                    'Video entrevista por alumno',
                    'Video Clip de las sesiones de fotos',
                    'Drone para la fiesta de promoción',
                    'Reel 3 minutos resumen de la fiesta',
                    'Video editado 120 minutos',
                    'Cortesía: asesoría en planificación del evento, asistencia a dos reuniones',
                    'Nota: +15 alumnos → cuadro laminado 40x30 para el docente',
                    'Nota: +20 alumnos → cuadro de vidrio 45x30 para el docente',
                    'Nota: válido para grupo de 14 alumnos hacia adelante',
                ]),
            ],
        ];

        $this->db->table('paquetes')->insertBatch($data);
    }
}
